name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Test java
      run: |
       java -version
       which java
       java -jar target/ducky-crm-0.3.0.war
    - name: Synopsys Detect Action
      id: detect
      uses: gautambaghel/synopsys-detect@v1
      env:
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
        BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the detect output time
      run: echo "The time was ${{ steps.detect.outputs.time }}"
